# Generated by Django 4.2.7 on 2023-12-09 03:04

from django.db import migrations, models
import django.db.models.deletion
import interfaces.vagas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.TextField(null=True)),
                ('employee_count', models.PositiveIntegerField(null=True)),
                ('followed', models.BooleanField(default=False)),
                ('platforms', models.JSONField(default=interfaces.vagas.models.Company.get_default_platforms)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('location', models.TextField()),
                ('workplace_type', models.TextField()),
                ('description', models.TextField()),
                ('platform_id', models.TextField()),
                ('platform', models.TextField()),
                ('applies', models.PositiveIntegerField(null=True)),
                ('application_url', models.TextField()),
                ('publication_date', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.company')),
                ('applied_to', models.BooleanField(null=True)),
                ('company_name', models.TextField(default=''))
            ],
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name_plural': 'listings'},
        ),
    ]
