# Generated by Django 4.2.7 on 2023-12-08 22:58

from django.db import migrations, models
import django.db.models.deletion
import interfaces.vagas_interface.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagem_url', models.TextField(null=True)),
                ('employee_count', models.PositiveIntegerField(null=True)),
                ('followed', models.BooleanField(default=False)),
                ('plataformas', models.JSONField(default=interfaces.vagas_interface.models.Empresa.get_default_platforms)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('local', models.TextField()),
                ('modalidade', models.TextField()),
                ('id_vaga', models.TextField()),
                ('plataforma', models.TextField()),
                ('n_candidaturas', models.PositiveIntegerField(null=True)),
                ('link_inscricao', models.TextField()),
                ('descricao', models.TextField()),
                ('tempo_publicado', models.TextField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas_interface.empresa')),
            ],
        ),
    ]
