# Generated by Django 4.2.7 on 2023-12-04 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('linkedin_id', models.TextField(null=True)),
                ('linkedin_nome', models.TextField(null=True)),
                ('linkedin_seguidores', models.TextField(null=True)),
                ('imagem_url', models.TextField(null=True)),
                ('employee_count', models.PositiveIntegerField(null=True)),
                ('glassdoor_id', models.TextField(null=True)),
                ('glassdoor_nome', models.TextField(null=True)),
                ('followed', models.BooleanField(default=False)),
                ('last_check', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('local', models.TextField()),
                ('modalidade', models.TextField(choices=[['l', 'Presencial/Hibrido'], ['r', 'Remoto']], default='Presencial/Hibrido')),
                ('applications_count', models.PositiveIntegerField(null=True)),
                ('id_vaga', models.TextField()),
                ('plataforma', models.TextField(choices=[['li', 'LinkedIn'], ['gl', 'Glassdoor']])),
                ('n_candidaturas', models.TextField(null=True)),
                ('link_inscricao', models.TextField()),
                ('descricao', models.TextField()),
                ('tempo_publicado', models.TextField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas_interface.empresa')),
            ],
        ),
    ]
