# Generated by Django 4.2.7 on 2023-12-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas_interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name_plural': 'listings'},
        ),
        migrations.AddField(
            model_name='listing',
            name='applied_to',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='company_name',
            field=models.TextField(default='')
        )
    ]
